/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_gregpack_thewar_network_JNIMoveProducer */

#ifndef _Included_ru_gregpack_thewar_network_JNIMoveProducer
#define _Included_ru_gregpack_thewar_network_JNIMoveProducer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_gregpack_thewar_network_JNIMoveProducer
 * Method:    produceNextMove
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_gregpack_thewar_network_JNIMoveProducer_produceNextMove
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     ru_gregpack_thewar_network_JNIMoveProducer
 * Method:    getNameNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_gregpack_thewar_network_JNIMoveProducer_getNameNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
